# Generated by Django 2.2.16 on 2023-04-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230410_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Введите текст комментария', max_length=100, verbose_name='Текст комментария'),
        ),
    ]
